apiVersion: v1
appVersion: "1.2.2"
description: Helm chart bacula_exporter for Kubernetes
name: bacula-exporter
version: 1.2.2
home: https://github.com/huntdatacenter/bacula_exporter
maintainers:
  - name: Gleb Goncharov
    email: g.goncharov@fun-box.ru
